import { writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Generates `Structures.jsx`: a module that re-exports every discovered
 * template's structure component via STATIC ES-module imports.
 *
 * Imports point DIRECTLY at the original template files under
 * `templates/<family>/<id>/<structure>` — nothing is copied. Remotion's
 * bundler resolves these paths at bundle time, so the static-import contract
 * is honored without materialising duplicates into `public/`.
 *
 * The lookup key is a composite `<safeFamily>-<safeTemplateId>-<structureFilename>`
 * (with `/` replaced by `-`), matching the key pipeline3 puts on each scene's
 * `structurePath` (see `engine/pipeline3/index.js`). The composite key is what
 * avoids collisions when multiple templates share a structure filename.
 */
export async function generateStructuresModule(templateRegistry, outputPath) {
  const imports = [];
  const exports = [];

  const moduleDir = path.dirname(outputPath);

  let importIndex = 0;
  for (const [, template] of templateRegistry.entries()) {
    const safeFamily = template.family.replace(/\//g, "-");
    const safeTemplateId = template.id.replace(/\//g, "-");
    for (const variation of template.variations ?? []) {
      const structureFilename = variation.structure;
      const srcPath = path.join(template.dir, structureFilename);
      // Relative path from the generated Structures.jsx back to the original
      // template file, e.g. "../templates/lists/basic/structure1.jsx".
      const relPath = path.relative(moduleDir, srcPath).replace(/\\/g, "/");
      const importName = `Structure_${importIndex++}`;
      const structureKey = `${safeFamily}-${safeTemplateId}-${structureFilename}`;
      imports.push(`import ${importName} from "${relPath}";`);
      exports.push(`  "${structureKey}": ${importName},`);
    }
  }

  const content = `// AUTO-GENERATED - Do not edit manually
// This file is generated by pipeline3/copyStructures.js before rendering.
// Imports point at the original template files under templates/<family>/<id>/;
// no structure files are copied anywhere.
${imports.join("\n")}

export const STRUCTURE_COMPONENTS = {
${exports.join("\n")}
};

export default STRUCTURE_COMPONENTS;
`;

  await writeFile(outputPath, content, "utf-8");
  return outputPath;
}
