import { copyFile, mkdir, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Copies all structure files from template registry to public/structures
 * with unique names (templateId + structure filename) for Remotion bundling.
 * Returns a map of structureKey -> uniquePublicPath for import generation.
 * The structureKey includes family+templateId+filename to avoid collisions.
 */
export async function copyStructureFiles(templateRegistry, publicDir) {
  const structuresDir = path.join(publicDir, "structures");
  await mkdir(structuresDir, { recursive: true });

  const structureMap = new Map(); // structureKey -> uniquePublicPath (relative to engine/pipeline3)

  for (const [templateId, template] of templateRegistry.entries()) {
    for (const variation of template.variations ?? []) {
      const structureFilename = variation.structure;
      const srcPath = path.join(template.dir, structureFilename);
      
      // Create unique name: family-templateId-structureFilename
      // e.g., "lists-basic-structure1.jsx"
      const safeFamily = template.family.replace(/\//g, "-");
      const safeTemplateId = template.id.replace(/\//g, "-");
      const uniqueName = `${safeFamily}-${safeTemplateId}-${structureFilename}`;
      const destPath = path.join(structuresDir, uniqueName);
      
      try {
        await copyFile(srcPath, destPath);
        // Use a composite key that includes family and templateId to avoid collisions
        const structureKey = `${safeFamily}-${safeTemplateId}-${structureFilename}`;
        // Path relative to engine/pipeline3/ for import
        structureMap.set(structureKey, `../../public/structures/${uniqueName}`);
      } catch (err) {
        console.warn(`Failed to copy structure ${srcPath}: ${err.message}`);
      }
    }
  }

  return structureMap;
}

/**
 * Generates a module that re-exports all structure components for static import.
 * This file is written to engine/pipeline3/Structures.jsx before bundling.
 */
export async function generateStructuresModule(structureMap, outputPath) {
  const imports = [];
  const exports = [];

  let importIndex = 0;
  for (const [structureKey, publicPath] of structureMap.entries()) {
    const importName = `Structure_${importIndex++}`;
    imports.push(`import ${importName} from "${publicPath}";`);
    exports.push(`  "${structureKey}": ${importName},`);
  }

  const content = `// AUTO-GENERATED - Do not edit manually
// This file is generated by pipeline3/copyStructures.js before rendering
${imports.join("\n")}

export const STRUCTURE_COMPONENTS = {
${exports.join("\n")}
};

export default STRUCTURE_COMPONENTS;
`;

  await import("node:fs/promises").then(fs => fs.writeFile(outputPath, content, "utf-8"));
  return outputPath;
}
