// AUTO-GENERATED - Do not edit manually
// This file is generated by pipeline3/copyStructures.js before rendering.
// Imports point at the original template files under templates/<family>/<id>/;
// no structure files are copied anywhere.
import Structure_0 from "../../templates/brand/anthropic-statement/structure1.jsx";
import Structure_1 from "../../templates/brand/anthropic-statement/structure2.jsx";
import Structure_2 from "../../templates/comparison/before-after/structure1.jsx";
import Structure_3 from "../../templates/comparison/checklist/structure1.jsx";
import Structure_4 from "../../templates/comparison/diff-row/structure1.jsx";
import Structure_5 from "../../templates/comparison/pro-con/structure1.jsx";
import Structure_6 from "../../templates/comparison/side-by-side/structure1.jsx";
import Structure_7 from "../../templates/gallery/captioned-row/structure1.jsx";
import Structure_8 from "../../templates/gallery/collage/structure1.jsx";
import Structure_9 from "../../templates/gallery/grid/structure1.jsx";
import Structure_10 from "../../templates/gallery/single-image-zoom/structure1.jsx";
import Structure_11 from "../../templates/gallery/stack/structure1.jsx";
import Structure_12 from "../../templates/hero/banner-strip/structure1.jsx";
import Structure_13 from "../../templates/hero/center-statement/structure1.jsx";
import Structure_14 from "../../templates/hero/quote-hero/structure1.jsx";
import Structure_15 from "../../templates/hero/split-byline/structure1.jsx";
import Structure_16 from "../../templates/hero/tagline-overlay/structure1.jsx";
import Structure_17 from "../../templates/hero/title-card/structure1.jsx";
import Structure_18 from "../../templates/hero/title-card/structure2.jsx";
import Structure_19 from "../../templates/lists/basic/structure1.jsx";
import Structure_20 from "../../templates/lists/basic/structure2.jsx";
import Structure_21 from "../../templates/quote/pull-quote/structure1.jsx";
import Structure_22 from "../../templates/stat/badge/structure1.jsx";
import Structure_23 from "../../templates/stat/grid/structure1.jsx";
import Structure_24 from "../../templates/stat/headline/structure1.jsx";
import Structure_25 from "../../templates/stat/headline/structure2.jsx";
import Structure_26 from "../../templates/stat/headline/structure3.jsx";
import Structure_27 from "../../templates/stat/two-up/structure1.jsx";
import Structure_28 from "../../templates/stat/with-icon/structure1.jsx";
import Structure_29 from "../../templates/timeline/journey/structure1.jsx";
import Structure_30 from "../../templates/timeline/linear/structure1.jsx";
import Structure_31 from "../../templates/timeline/milestones/structure1.jsx";
import Structure_32 from "../../templates/timeline/phases/structure1.jsx";
import Structure_33 from "../../templates/timeline/vertical-steps/structure1.jsx";

export const STRUCTURE_COMPONENTS = {
  "brand-anthropic-statement-structure1.jsx": Structure_0,
  "brand-anthropic-statement-structure2.jsx": Structure_1,
  "comparison-before-after-structure1.jsx": Structure_2,
  "comparison-checklist-structure1.jsx": Structure_3,
  "comparison-diff-row-structure1.jsx": Structure_4,
  "comparison-pro-con-structure1.jsx": Structure_5,
  "comparison-side-by-side-structure1.jsx": Structure_6,
  "gallery-captioned-row-structure1.jsx": Structure_7,
  "gallery-collage-structure1.jsx": Structure_8,
  "gallery-grid-structure1.jsx": Structure_9,
  "gallery-single-image-zoom-structure1.jsx": Structure_10,
  "gallery-stack-structure1.jsx": Structure_11,
  "hero-banner-strip-structure1.jsx": Structure_12,
  "hero-center-statement-structure1.jsx": Structure_13,
  "hero-quote-hero-structure1.jsx": Structure_14,
  "hero-split-byline-structure1.jsx": Structure_15,
  "hero-tagline-overlay-structure1.jsx": Structure_16,
  "hero-title-card-structure1.jsx": Structure_17,
  "hero-title-card-structure2.jsx": Structure_18,
  "lists-basic-structure1.jsx": Structure_19,
  "lists-basic-structure2.jsx": Structure_20,
  "quote-pull-quote-structure1.jsx": Structure_21,
  "stat-badge-structure1.jsx": Structure_22,
  "stat-grid-structure1.jsx": Structure_23,
  "stat-headline-structure1.jsx": Structure_24,
  "stat-headline-structure2.jsx": Structure_25,
  "stat-headline-structure3.jsx": Structure_26,
  "stat-two-up-structure1.jsx": Structure_27,
  "stat-with-icon-structure1.jsx": Structure_28,
  "timeline-journey-structure1.jsx": Structure_29,
  "timeline-linear-structure1.jsx": Structure_30,
  "timeline-milestones-structure1.jsx": Structure_31,
  "timeline-phases-structure1.jsx": Structure_32,
  "timeline-vertical-steps-structure1.jsx": Structure_33,
};

export default STRUCTURE_COMPONENTS;
