// AUTO-GENERATED - Do not edit manually
// This file is generated by pipeline3/copyStructures.js before rendering
import Structure_0 from "../../public/structures/lists-basic-structure1.jsx";
import Structure_1 from "../../public/structures/lists-basic-structure2.jsx";
import Structure_2 from "../../public/structures/quote-pull-quote-structure1.jsx";

export const STRUCTURE_COMPONENTS = {
  "lists-basic-structure1.jsx": Structure_0,
  "lists-basic-structure2.jsx": Structure_1,
  "quote-pull-quote-structure1.jsx": Structure_2,
};

export default STRUCTURE_COMPONENTS;
