import React from "react";
import { Composition, getInputProps, registerRoot, AbsoluteFill } from "remotion";
import { STRUCTURE_COMPONENTS } from "../engine/pipeline3/Structures.jsx";

/**
 * Remotion entry for single-variation preview rendering.
 * The preview MP4s served by the gallery are produced by bundling this file
 * once and running renderMedia per variation with inputProps = { variation }.
 *
 * `variation` carries `structureKey` (the composite key into STRUCTURE_COMPONENTS
 * generated by engine/pipeline3/copyStructures.js), plus `defaultContent`,
 * `style`, and `animation` — the same shape pipeline3 hands to <StoryboardVideo>
 * per-scene, minus the timing/transition envelope.
 */

const SingleVariation = ({ variation }) => {
  const Comp = STRUCTURE_COMPONENTS[variation.structureKey];
  if (!Comp) {
    return (
      <AbsoluteFill style={{ background: "#000", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontFamily: "sans-serif" }}>
        <div>Missing structure: {variation.structureKey}</div>
      </AbsoluteFill>
    );
  }
  return (
    <Comp
      content={variation.defaultContent}
      style={variation.style}
      animation={variation.animation}
    />
  );
};

export const RemotionRoot = () => {
  const { variation } = getInputProps();
  return (
    <Composition
      id="SingleVariation"
      component={SingleVariation}
      fps={30}
      width={1080}
      height={1920}
      durationInFrames={150}
      defaultProps={{ variation }}
    />
  );
};

registerRoot(RemotionRoot);
