#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PRIMARY_TEMPLATE_ROOT = path.join(__dirname, "..", "..", "templates");
const SECONDARY_TEMPLATE_ROOT = path.join(__dirname, "..", "..", "templates-secondary");

function discoverTemplates(rootDir) {
  const templates = [];

  function walk(dir, prefix = "") {
    if (!fs.existsSync(dir)) return;

    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const tplDir = path.join(dir, entry.name);
      const manifestPath = path.join(tplDir, "manifest.json");
      const componentPath = path.join(tplDir, "index.jsx");

      // Check if this directory is a template (has both manifest.json and index.jsx)
      if (fs.existsSync(manifestPath) && fs.existsSync(componentPath)) {
        let manifest;
        try {
          manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
        } catch (e) {
          continue;
        }

        if (!manifest.key) continue;

        // Create a unique key by prefixing with the folder path (excluding root)
        // This allows nested templates with same name to coexist
        const uniqueKey = prefix ? prefix + "-" + manifest.key : manifest.key;

        // Calculate path relative to __dirname (where templateRegistry.js lives)
        const relComponentPath = path.relative(__dirname, componentPath).replace(/\\/g, "/");
        const relManifestPath = path.relative(__dirname, manifestPath).replace(/\\/g, "/");

        templates.push({
          key: uniqueKey,
          originalKey: manifest.key,
          componentPath: "./" + relComponentPath,
          manifestPath: "./" + relManifestPath,
          manifest
        });
      }

      // Always recurse into subdirectories (template family folders)
      const newPrefix = prefix ? prefix + "-" + entry.name : entry.name;
      walk(tplDir, newPrefix);
    }
  }

  walk(rootDir);
  return templates;
}

function generateStaticRegistryContent() {
  const primaryTemplates = discoverTemplates(PRIMARY_TEMPLATE_ROOT);
  const secondaryTemplates = discoverTemplates(SECONDARY_TEMPLATE_ROOT);
  const allTemplates = [...primaryTemplates, ...secondaryTemplates];
  
  // Sort with fallback first, then alphabetical
  allTemplates.sort((a, b) => {
    if (a.key === "_fallback") return -1;
    if (b.key === "_fallback") return 1;
    return a.key.localeCompare(b.key);
  });
  
  const imports = allTemplates.map(tpl => {
    const varName = tpl.key.replace(/[^a-zA-Z0-9_$]/g, "") + "Template";
    return `import ${varName} from "${tpl.componentPath}";`;
  }).join("\n");
  
  const registryEntries = allTemplates.map(tpl => {
    const varName = tpl.key.replace(/[^a-zA-Z0-9_$]/g, "") + "Template";
    return `  "${tpl.key}": ${varName},`;
  }).join("\n");
  
  return `/**
 * Remotion's bundler (webpack) needs statically analyzable imports to
 * include each template's component in the render bundle. Because the
 * scoring engine can in principle discover new template folders at runtime,
 * every template that should be renderable MUST be registered here as well
 * -- discovery and rendering are deliberately decoupled.
 *
 * Template discovery is recursive: template family folders can contain
 * nested template folders, allowing hierarchical organization.
 * Nested templates get keys prefixed with their folder path (e.g., "anthropic-templates-stat-highlight").
 *
 * AUTO-GENERATED by populateRegistry.js -- DO NOT EDIT MANUALLY.
 * Run: node src/pipeline3/populateRegistry.js --regenerate
 */
${imports}

export const TEMPLATE_REGISTRY = {
${registryEntries}
};

export function resolveTemplateComponent(templateKey) {
  const Component = TEMPLATE_REGISTRY[templateKey];
  if (!Component) {
    throw new Error(
      \`No registered component for template key "\${templateKey}". \` +
        "Add it to src/pipeline3/templateRegistry.js."
    );
  }
  return Component;
}
`;
}

function regenerateStaticRegistry() {
  const content = generateStaticRegistryContent();
  const registryPath = path.join(__dirname, "templateRegistry.js");
  fs.writeFileSync(registryPath, content, "utf-8");
  const primaryTemplates = discoverTemplates(PRIMARY_TEMPLATE_ROOT);
  const secondaryTemplates = discoverTemplates(SECONDARY_TEMPLATE_ROOT);
  console.log("[templateRegistry] Regenerated " + registryPath);
  console.log("[templateRegistry] Registered " + (primaryTemplates.length + secondaryTemplates.length) + " templates");
  for (const t of primaryTemplates.concat(secondaryTemplates)) {
    console.log("  - " + t.key + (t.key !== t.originalKey ? " (was " + t.originalKey + ")" : ""));
  }
}

function listAvailableTemplates() {
  const primaryTemplates = discoverTemplates(PRIMARY_TEMPLATE_ROOT);
  const secondaryTemplates = discoverTemplates(SECONDARY_TEMPLATE_ROOT);
  const allTemplates = [...primaryTemplates, ...secondaryTemplates];
  console.log("Available templates:");
  for (const tpl of allTemplates) {
    console.log(`  ${tpl.key}: ${tpl.manifest.description} (${tpl.manifest.capacity.minChars}-${tpl.manifest.capacity.maxChars} chars)`);
  }
}

const args = process.argv.slice(2);
if (args.includes("--regenerate") || args.includes("-r")) {
  regenerateStaticRegistry();
} else if (args.includes("--list") || args.includes("-l")) {
  listAvailableTemplates();
} else {
  console.log("Usage:");
  console.log("  node src/pipeline3/populateRegistry.js --regenerate  # Regenerate static templateRegistry.js");
  console.log("  node src/pipeline3/populateRegistry.js --list        # List discovered templates");
}
