/**
 * Remotion's bundler (webpack) needs statically analyzable imports to
 * include each template's component in the render bundle. Because the
 * scoring engine can in principle discover new template folders at runtime,
 * every template that should be renderable MUST be registered here as well
 * -- discovery and rendering are deliberately decoupled.
 *
 * AUTO-GENERATED by populateRegistry.js -- DO NOT EDIT MANUALLY.
 * Run: node src/pipeline3/populateRegistry.js --regenerate
 */
import _fallbackTemplate from "./../../templates/_fallback/index.jsx";
import bulletlistTemplate from "./../../templates/bullet-list/index.jsx";
import imagepanelTemplate from "./../../templates/image-panel/index.jsx";
import quoteTemplate from "./../../templates/quote/index.jsx";
import titlecardTemplate from "./../../templates/title-card/index.jsx";

export const TEMPLATE_REGISTRY = {
  "_fallback": _fallbackTemplate,
  "bullet-list": bulletlistTemplate,
  "image-panel": imagepanelTemplate,
  "quote": quoteTemplate,
  "title-card": titlecardTemplate,
};

export function resolveTemplateComponent(templateKey) {
  const Component = TEMPLATE_REGISTRY[templateKey];
  if (!Component) {
    throw new Error(
      `No registered component for template key "${templateKey}". ` +
        "Add it to src/pipeline3/templateRegistry.js."
    );
  }
  return Component;
}
